version: "2"
services:
  worker:
    build: .
    tty: true
    environment:
      DEBUG: 'False'
      BROKER: 'amqp://hhsrc:hhsrc@172.19.0.1:5672/hhsrc'
      BACKEND: 'redis://:hhsrc@172.19.0.1:6379/2'
      TZ: Asia/Shanghai
    restart: always
