version: "2"
services:
  worker:
    build: .
    tty: true
    environment:
      DEBUG: 'False'
      BROKER: 'amqp://hhsrc:hhsrc@172.19.0.1:5672/hhsrc_broker'
      BACKEND: 'amqp://hhsrc:hhsrc@172.19.0.1:5672/hhsrc_backend'
      TZ: Asia/Shanghai
    restart: always
