version: "2"
services:
  hhsrc_server:
    build: .
    tty: true
    environment:
      DEBUG: 'False'
    restart: always
    ports:
      - "5000:5000"
      - "5555:5555"
  rabbitmq:
    image: rabbitmq:3.8.3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5672:5672
      - 15673:15672
    environment:
      - RABBITMQ_DEFAULT_VHOST=hhsrc_broker
      - RABBITMQ_DEFAULT_USER=hhsrc
      - RABBITMQ_DEFAULT_PASS=hhsrc
    networks:
      - hhsrc_app
networks:
  hhsrc_app:
    driver: bridge